
module.exports = function (app) {
  const data = [
    {
      name: 'iphone 6',
      category: 'smartphones',
      color: 'gold',
      condition: 'new',
      damaged: false,
      price: 1999,
      delivery_cost: 35,
      start_date: '2018-06-01T17:16:39.259Z',
      finish_date: '2018-07-01T17:16:39.260Z',
      path_image: '../../../assets/images/iphone6.jpeg',
      description: 'iphone6sssgss',
      clientname: "Jan",
      clientsurname: "Kowalski",
      clientcity: "Trokajny",
      clientphone: 6000000,
      clientmail: "example@gmail.com",

    },
    {
      name: 'Macbook Air',
      category: 'laptops',
      color: 'white',
      condition: 'new',
      damaged: false,
      price: 2500,
      delivery_cost: 50,
      start_date: '2018-06-01T17:16:39.259Z',
      finish_date: '2018-07-01T17:16:39.260Z',
      path_image: '../../../assets/images/MacbookAir.jpeg',
      description: 'iphone6sssgsscsdss',
      clientname: "Jan",
      clientsurname: "Kowalski",
      clientcity: "Trokajny",
      clientphone: 6000000,
      clientmail: "example@gmail.com",
    },
    {
      name: 'Iphone 7',
      category: 'smartphones',
      color: 'gold',
      condition: 'used',
      damaged: false,
      price: 1999,
      delivery_cost: 35,
      start_date: '2018-06-01T17:16:39.259Z',
      finish_date: '2018-07-01T17:16:39.260Z',
      path_image: '../../../assets/images/iphone7.jpeg',
      description: 'iphone6sssdsdsdsdgss',
      clientname: "Jan",
      clientsurname: "Kowalski",
      clientcity: "Trokajny",
      clientphone: 6000000,
      clientmail: "example@gmail.com",
    },
    {
      name: 'Iphone 8',
      category: 'smartphones',
      color: 'gold',
      condition: 'new',
      damaged: true,
      price: 1999,
      delivery_cost: 35,
      start_date: '2018-06-01T17:16:39.259Z',
      finish_date: '2018-07-01T17:16:39.260Z',
      path_image: '../../../assets/images/iphone8.jpeg',
      description: 'iphone6sssgssdsdsdsdwwewe',
      clientname: "Jan",
      clientsurname: "Nowak",
      clientcity: "Trokajny",
      clientphone: 6000000,
      clientmail: "example@gmail.com",
    },
    {
      name: 'Iphone 6',
      category: 'smartphones',
      color: 'gold',
      condition: 'used',
      damaged: false,
      price: 1999,
      delivery_cost: 35,
      start_date: '2018-06-01T17:16:39.259Z',
      finish_date: '2018-07-01T17:16:39.260Z',
      path_image: '../../../assets/images/iphone6.jpeg',
      description: 'iphonsdse6sssgss',
      clientname: "Jan",
      clientsurname: "Kowalski",
      clientcity: "Trokajny",
      clientphone: 6000000,
      clientmail: "example@gmail.com",
    },
    {
      name: 'Iphone X Plus',
      category: 'smartphones',
      color: 'gold',
      condition: 'used',
      damaged: false,
      price: 1999,
      delivery_cost: 35,
      start_date: '2018-06-01T17:16:39.259Z',
      finish_date: '2018-07-01T17:16:39.260Z',
      path_image: '../../../assets/images/iphoneX.jpeg',
      description: 'iphone6sssgssdsds',
      clientname: "Marian",
      clientsurname: "Kowalski",
      clientcity: "Trokajny",
      clientphone: 6000000,
      clientmail: "example@gmail.com",
    },
    {
      name: 'Iphone X',
      category: 'smartphones',
      color: 'gold',
      condition: 'used',
      damaged: false,
      price: 1999,
      delivery_cost: 35,
      start_date: '2018-06-01T17:16:39.259Z',
      finish_date: '2018-07-01T17:16:39.260Z',
      path_image: '../../../assets/images/iphoneX.jpeg',
      description: 'iphone6sssgssdsdsds',
      clientname: "Jan",
      clientsurname: "Kowalski",
      clientcity: "Trokajny",
      clientphone: 6000000,
      clientmail: "example@gmail.com",
    },
    {
      name: 'Samsung S8',
      category: 'smartphones',
      color: 'silver',
      condition: 'used',
      damaged: true,
      price: 567,
      delivery_cost: 35,
      start_date: '2018-06-01T17:16:39.259Z',
      finish_date: '2018-07-01T17:16:39.260Z',
      path_image: '../../../assets/images/iphoneX.jpeg',
      description: 'iphone6ssssddssamsunggss',
      clientname: "Jan",
      clientsurname: "Kowalski",
      clientcity: "Trokajny",
      clientphone: 6000000,
      clientmail: "example@gmail.com",
    },
    {
      name: 'Samsung S8',
      category: 'smartphones',
      color: 'silver',
      condition: 'used',
      damaged: true,
      price: 567,
      delivery_cost: 35,
      start_date: '2018-06-01T17:16:39.259Z',
      finish_date: '2018-07-01T17:16:39.260Z',
      path_image: '../../../assets/images/iphoneX.jpeg',
      description: 'iphone6ssdssdsgfgfsgss',
      clientname: "Jan",
      clientsurname: "Kowalski",
      clientcity: "Trokajny",
      clientphone: 6000000,
      clientmail: "example@gmail.com",
    },
    {
      name: 'Samsung S8',
      category: 'smartphones',
      color: 'silver',
      condition: 'used',
      damaged: true,
      price: 567,
      delivery_cost: 35,
      start_date: '2018-06-01T17:16:39.259Z',
      finish_date: '2018-08-01T17:16:39.260Z',
      path_image: '../../../assets/images/iphoneX.jpeg',
      description: 'iphone6ssdsdssgss',
      clientname: "Jan",
      clientsurname: "Kowalski",
      clientcity: "Trokajny",
      clientphone: 6000000,
      clientmail: "example@gmail.com",
    },
    {
      name: 'Samsung S8',
      category: 'smartphones',
      color: 'silver',
      condition: 'used',
      damaged: true,
      price: 567,
      delivery_cost: 35,
      start_date: '2018-06-01T17:16:39.259Z',
      finish_date: '2018-11-10T17:16:39.260Z',
      path_image: '../../../assets/images/iphoneX.jpeg',
      description: 'iphone6ssssdsdsgss',
      clientname: "Jan",
      clientsurname: "Kowalski",
      clientcity: "Trokajny",
      clientphone: 6000000,
      clientmail: "example@gmail.com",
    },
    {
      name: 'Samsung S8',
      category: 'smartphones',
      color: 'silver',
      condition: 'used',
      damaged: true,
      price: 567,
      delivery_cost: 35,
      start_date: '2018-06-01T17:16:39.259Z',
      finish_date: '2018-12-01T17:16:39.260Z',
      path_image: '../../../assets/images/iphoneX.jpeg',
      description: 'iphone6sssgsdsdsdss',
      clientname: "Jan",
      clientsurname: "Kowalski",
      clientcity: "Trokajny",
      clientphone: 6000000,
      clientmail: "example@gmail.com",
    },
    {
      name: 'Samsung S8',
      category: 'smartphones',
      color: 'silver',
      condition: 'used',
      damaged: true,
      price: 567,
      delivery_cost: 35,
      start_date: '2018-06-01T17:16:39.259Z',
      finish_date: '2018-09-21T17:16:39.260Z',
      path_image: '../../../assets/images/iphoneX.jpeg',
      description: 'iphone6sdsdsssgss',
      clientname: "Jan",
      clientsurname: "Kowalski",
      clientcity: "Trokajny",
      clientphone: 6000000,
      clientmail: "example@gmail.com",
    },
    {
      name: 'Samsung S8',
      category: 'smartphones',
      color: 'silver',
      condition: 'used',
      damaged: true,
      price: 567,
      delivery_cost: 35,
      start_date: '2018-06-01T17:16:39.259Z',
      finish_date: '2018-10-06T17:16:39.260Z',
      path_image: '../../../assets/images/iphoneX.jpeg',
      description: 'iphodssdsne6sssgss',
      clientname: "Jan",
      clientsurname: "Kowalski",
      clientcity: "Trokajny",
      clientphone: 6000000,
      clientmail: "example@gmail.com",
    },
    {
      name: 'Samsung S8',
      category: 'smartphones',
      color: 'silver',
      condition: 'used',
      damaged: true,
      price: 567,
      delivery_cost: 35,
      start_date: '2018-06-01T17:16:39.259Z',
      finish_date: '2018-08-01T17:16:39.260Z',
      path_image: '../../../assets/images/iphoneX.jpeg',
      description: 'iphone6sssgsssdsds',
      clientname: "Jan",
      clientsurname: "Kowalski",
      clientcity: "Trokajny",
      clientphone: 6000000,
      clientmail: "example@gmail.com",
    },
    {
      name: 'Samsung QLed Tv',
      category: 'Tv',
      color: 'gold',
      condition: 'true',
      damaged: false,
      price: 2800,
      delivery_cost: 78,
      start_date: '2018-06-01T17:16:39.259Z',
      finish_date: '2018-09-01T17:16:39.260Z',
      path_image: '../../../assets/images/Samsung_Qled.jpeg',
      description: 'Samsung QLed',
      clientname: "Jan",
      clientsurname: "Kowalski",
      clientcity: "Trokajny",
      clientphone: 6000000,
      clientmail: "example@gmail.com",
    },


  ];

  var db = app.dataSources.db;
  const ShopModel = app.models.Shopitems || db.buildModelFromInstance('shopitems', data, {idInjection: true});

  data.map(function (shopitems) {
    ShopModel.create(shopitems, function (err, u) {
      if (err) {
        throw err;
      }
    });
  })
}
